name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Auto cancel
        uses: technote-space/auto-cancel-redundant-job@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache
        uses: actions/cache@v4
        with:
          path: yarn cache dir
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          npm set-script prepare ""
          yarn install --frozen-lockfile

      - name: Format
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Compile
        run: yarn tsc

      - name: Test
        run: yarn test:ci:coverage

      - name: Build
        run: yarn build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
